# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  lane :release do
    increment_build_number(xcodeproj: "KyotoTrip.xcodeproj")
    build_app(
      workspace: "KyotoTrip.xcworkspace",
      clean: true,
      scheme: "Release_KyotoTrip",
      xcargs: "MGL_MAPBOX_ACCESSTOKEN=ENV['MGL_MAPBOX_ACCESSTOKEN'] GNAVI_ACCESSTOKEN=ENV['GNAVI_ACCESSTOKEN']"
    )
    set_build_number_repository
    upload_to_app_store(skip_metadata: true, skip_screenshots: true)
  end

  lane :tests do
  run_tests(workspace: "KyotoTrip.xcworkspace",
            devices: ["iPhone 8"],
            scheme: "Develop_KyotoTrip")
  end

  lane :release_with_githubactions do
    import_certificates_and_provisioning_profile
    set_build_number_repository
    build_app(
      workspace: "KyotoTrip.xcworkspace",
      clean: true,
      scheme: "Release_KyotoTrip",
      xcargs: "MGL_MAPBOX_ACCESSTOKEN=ENV['MGL_MAPBOX_ACCESSTOKEN'] GNAVI_ACCESSTOKEN=ENV['GNAVI_ACCESSTOKEN']"
    )
    upload_to_app_store(skip_metadata: true, skip_screenshots: true)
  end

  desc "Import Certificates and Provisioning Profile"
    private_lane :import_certificates_and_provisioning_profile do
        create_keychain(
            name: "mykeychain",
            password: "",
            timeout: 1800
        )
        import_certificate(
            certificate_path: "ios_distribution.p12",
            certificate_password: "",
            keychain_name: "mykeychain",
            keychain_password: ""
        )
        install_provisioning_profile(path: "kyoto_trip.mobileprovision")
    end
end
